ALFATEX4TRADE/Models/Primission.cs
namespace ALFATEX4TRADE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public  class Primission
    {
        public int ID { get; set; }

         [Display(Name = "Stock Request Number")]

        public int PrimNumber { get; set; }

       [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]

        public DateTime? Date { get; set; }

                      [Display(Name = "Account Code")]

        public string ClientID { get; set; }

                      [Display(Name = "Product Code")]

        public string ProductID { get; set; }

                      [Display(Name = "Description")]

        public string ProductName { get; set; }


        public double Outgoing { get; set; }

                      [Display(Name = "Account")]

        public string CleintName { get; set; }
    }
}

ALFATEX4TRADE/Controllers/PrimissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ALFATEX4TRADE.Models;

namespace ALFATEX4TRADE.Controllers
{
    public class PrimissionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationDbContext db2 = new ApplicationDbContext() ;
        public int ReqN = new int ();
        public DateTime ReqDate = new DateTime();

        // GET: Primissions
         [Authorize]

        public ActionResult Index()
        {
            int n = 0;
            foreach (var i in db.Primission)
            {
                if (i.PrimNumber > n && i.Date == DateTime.Today) n = i.PrimNumber;
            }
            return View(db.Primission.Where(x => x.PrimNumber == n && x.Date == DateTime.Today).ToList());
        }
        [HttpPost]
        public ActionResult Index(Primission pr ) 
        {
            if (ModelState.IsValid)
            {
                return View(db.Primission.Where(x => x.PrimNumber == pr.PrimNumber && x.Date == pr.Date).ToList());
            }

            return RedirectToAction("Index");
        }

        public JsonResult GetProduct()
        {
            List<ProductRecord> ProductName = new List<ProductRecord>();
            foreach (var i in db.Product)
            {
                ProductName.Add(new ProductRecord
                {
                    ProductID = (i.ProductID).ToString() ,
                    ProductName = (i.Description).ToString()

                });
            }
            return Json(ProductName, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetName()
        {
            List<DailyTradeRecord> IdName = new List<DailyTradeRecord>();
            foreach (var i in db.Cleint)
            {
                IdName.Add(new DailyTradeRecord
                {
                    AccountID = (i.AccountID).ToString() ,
                    AccountName = (i.AccountName).ToString()

                });
            }
            return Json(IdName, JsonRequestBehavior.AllowGet);
        }




         [Authorize]
          public ActionResult Create()
        {
            return View();
        }

          [HttpPost]
          public ActionResult Create (RequestForm rf)
          {
              int ReqNum = 0;
              DateTime date = DateTime.Today;
              foreach (var i in db.Primission)
              {
                  if (i.Date == date && i.PrimNumber > ReqNum)
                  {
                      ReqNum = i.PrimNumber;
                  }
              }

              ReqNum++;
              for (int i = 0; i < rf.ProductID.Count(); i++)
              {
                  if (rf.ProductID[i].Length == 0) continue;
                  Primission pr = new Primission();
                  ReqN = ReqNum;
                  ReqDate = date ;
                  pr.PrimNumber = ReqNum;
                  pr.Date = date;
                  pr.ClientID = rf.ClientID;
                  pr.CleintName = rf.CleintName;
                  pr.ProductID = rf.ProductID[i];
                  pr.ProductName = rf.ProductName[i];
                  pr.Outgoing = rf.Outgoing[i];
                  db.Primission.Add(pr);
                  db.SaveChanges();
              }
               
                return RedirectToAction("NewBill");
          }



           [Authorize]

          public ActionResult NewBill()
          {
              return View();
          }

        [HttpPost]
          public ActionResult NewBill(BillForm bl)
          {

                  int dn = 0;
                  bl.Date = DateTime.Today;
                  foreach (var i in db.Data)
                  {
                      if (i.DailyNum > dn && i.Date == bl.Date) dn = i.DailyNum;
                  }
                  dn++;
                  var rqnum = 0;
                  foreach (var i in db.Primission)
                  {
                      if (i.Date == DateTime.Today && i.PrimNumber > rqnum)
                      {
                          rqnum = i.PrimNumber;
                      }

                  }
                  double Gtotal = 0;
                  for (int i = 0; i < bl.ProductID.Count(); i++)
                  {
                      if (bl.ProductID[i].Length == 0) continue;
                      Bill b = new Bill();
                      b.DailyID = dn;
                      b.BillNumber = rqnum;
                      b.CleintName = bl.CleintName;
                      b.ClientID = bl.ClientID;
                      b.Date = DateTime.Today;
                      b.Outgoing = bl.Outgoing[i];
                      b.Price = bl.Price[i];
                      b.Bag = bl.Bag[i];
                      b.ProductID = bl.ProductID[i];
                      b.ProductName = bl.ProductName[i];
                      b.Size = bl.Size[i];
                      b.Total = bl.Total[i];
                      Gtotal += Convert.ToDouble( b.Total );
                      db.Bill.Add(b);
                      db.SaveChanges();
                  }





                  Data data = new Data();
                  data.AccountID = bl.ClientID;
                  data.AccountName = bl.CleintName;
                  data.DailyNum = dn;
                  data.Date = DateTime.Today;
                  data.DR = Convert.ToDouble(Gtotal);
                  db.Data.Add(data);
                  db.SaveChanges();

                  for (int i = 0; i < bl.ProductID.Count(); i++)
                  {
                      if (bl.ProductID[i].Length == 0) continue;
                      Data d = new Data() ;
                      d.DailyNum = dn;
                      d.Date = DateTime.Today;
                      foreach (var cur in db.Product)
                      {
                          if (cur.ProductID == bl.ProductID[i] )
                          {
                              d.AccountID = cur.ValueToID + cur.ProductID;
                              d.AccountName = cur.Size + cur.Description;
                              break;
                          }
                      }     
                      d.CR =Convert.ToDouble( bl.Total[i]);
                      db.Data.Add(d);
                      db.SaveChanges();
                  }
        
              return RedirectToAction("Index");
          }


         [Authorize]

        public ActionResult DisBill()
        {
            int n = 0;
            foreach (var i in db.Bill)
            {
                if (i.BillNumber > n && i.Date == DateTime.Today) n = Convert.ToInt32( i.BillNumber) ;
            }

            return View(db.Bill.Where(x => x.BillNumber == n && x.Date == DateTime.Today).ToList());
        }


        [HttpPost]
        public ActionResult DisBill( Bill bill)
        {
            if (ModelState.IsValid)
            {

                return View(db.Bill.Where(x => x.BillNumber == bill.BillNumber && x.Date == bill.Date).ToList());
            }
            return RedirectToAction("DisBill");
        }




        public JsonResult Display()
        {
            List<BillRecord> dis = new List<BillRecord>();
            int rn = 0;
            DateTime dt = new DateTime();
            foreach (var i in db.Primission)
            {
                if (i.PrimNumber > rn)
                {
                    rn = i.PrimNumber;
                    dt = Convert.ToDateTime(i.Date);
                }
            }
            foreach (var i in db.Primission)
            {
                if (i.Date == dt && i.PrimNumber == rn)
                {


                    Product pd = new Product();
                   pd = db2.Product.Find(i.ProductID);
                    dis.Add(new BillRecord
                    {
                        ReqNum = i.PrimNumber,
                        ClientID = i.ClientID,
                        CleintName = i.CleintName,
                        Date = i.Date,
                        ProductID = i.ProductID,
                        ProductName = i.ProductName,
                        Outgoing = i.Outgoing,
                        Size = pd.Size,
                        Price = Convert.ToDouble(pd.Price) 


                    });
                }

            }
            return Json(dis, JsonRequestBehavior.AllowGet);
        }





        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(Primission pr )
        {
            if (ModelState.IsValid)
            {
                foreach (var i in db.EditReq)
                {
                    db.EditReq.Remove(i);
             //       db.SaveChanges();
                }
                EditRequest e = new EditRequest();
                e.PrimNumber =Convert.ToInt32 (pr.PrimNumber) ;
                e.Date = pr.Date;
                db.EditReq.Add(e);
                db.SaveChanges();
                return RedirectToAction("EditReq");
            }
            return View();
        }
        public ActionResult EditReq()
        {
            return View();
        }


        [HttpPost]
        public ActionResult EditReq(RequestForm rf )
        {
            int ReqNum = 0;
            int JournalNum = 0;
            DateTime date = new DateTime() ;
            foreach (var i in db.EditReq)
            {
                    ReqNum = i.PrimNumber;
                    date = Convert.ToDateTime(i.Date);
                    break;
            }

            foreach (var i in db.Primission)
            {
                if (i.PrimNumber == ReqNum)
                {
                    db.Primission.Remove(i);
       //             db.SaveChanges();
                }
            }

            foreach (var i in db.Bill)
            {
                if (i.BillNumber == ReqNum)
                {

ALFATEX4TRADE/Views/Primissions/Create.cshtml
@model ALFATEX4TRADE.Models.RequestForm

@{
    ViewBag.Title = "Create";
}

<h2> New Stock Request</h2>



@using (Html.BeginForm("Create", "Primissions", FormMethod.Post))
{

    <div align="center">

        <div class="form-inline ">
            <div class="form-group" style="margin-right:25px">
                @Html.TextBoxFor(m => Model.ClientID, new
           {
               @id = "CID",
               @class = "passcleint form-control",
               autocomplete = "off",
               @placeholder = " Cleint Code "
 })

            </div>
            <div class="form-group" style="margin-right:25px">

                @Html.TextBoxFor(m => Model.CleintName, new
           {
               @id = "printcleint",
               autocomplete = "off",
               @class = "form-control",
               @placeholder = " Cleint Name "
         })


            </div>


        </div>
    </div>
    
    
    <table class=" table-bordered" align="center"
           style="margin-top:50px; border:solid ; ">
        <tr style="border:solid; ">
            <th style="text-align:center;border-right:solid">
                <p>Product Code </p>
            </th>
            <th style="text-align:center;border-right:solid">
                <p >Product Description </p>
            </th>
            <th style="text-align:center;">
                <p>Outgoing</p>   
            </th>

        </tr>

        @for (int i = 0; i < 30; i++)
        {  
        <tr>
  
            <td>
                @Html.TextBoxFor(m => Model.ProductID, new {  @id = "PID"+i , autocomplete = "off", @class = "passP form-control" })
            </td>

            <td>
                @Html.TextBoxFor(m => Model.ProductName, new { @class = "form-control", @id = "printproduct" + i, autocomplete = "off" })

            </td>

            <td>
                @Html.TextBoxFor(m => Model.Outgoing, new { type = "number", min = "0", step = "1", autocomplete = "off", @class = "form-control" })
            </td>

        </tr>
        }
    </table>



    <div align="center" style="margin-top:20px ">
        <input type="submit" value="  Post  " class="btn btn-default" style="font-size: 20px" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.12.4.js"></script>


<script>

    $(document).ready(function () {

        $(window).keydown(function (event) {
            if (event.keyCode == 13) {
                event.preventDefault();
                return false;
            }
        });



        $("#CID").on('change', function () {
            var id = $("#CID").val();
            var Name;
            $(function () {
                $.get("GetName", {}, function (data) {
                    $.each(data, function (index, value) {
                        if (value.AccountID == id) {
                            Name = value.AccountName;
                        }
                    });

                        $("#printcleint").val(Name);

                });
            });

        });




        $(".passP").on('change', function () {
            var id = $(this).val();
            var ID = $(this).closest(".passP").attr("id");
            var Name;
            $(function () {
                $.get("GetProduct", {}, function (data) {
                    $.each(data, function (index, value) {
                        if (value.ProductID == id) {
                            Name = value.ProductName;
                        }
                    });
                    var last;
                    if (ID.length == 4) last = ID[3];
                    else last = ID[3] + ID[4];
                    $("#printproduct" + last).val(Name);

                });
            });

        });

    });
</script>

ALFATEX4TRADE/Views/Primissions/DisBill.cshtml
@model IEnumerable<ALFATEX4TRADE.Models.Bill>
@{
    ViewBag.Title = "DisBill";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var i = 1;

    double GeneralTotal = 0;
    double GBags = 0;

    double Goutgoing = 0;
    foreach (var j in Model)
    {
        GBags += Convert.ToDouble(j.Bag);
        Goutgoing += Convert.ToDouble(j.Outgoing);
        GeneralTotal += Convert.ToDouble(j.Total);

    }
}

<h2>Display Bill</h2>


<div align="center" >
    @using (Html.BeginForm("DisBill", "Primissions", FormMethod.Post))
    {

        <div class="form-inline ">
            <div class="form-group" style="margin-right:25px">
                @Html.TextBox("BillNumber", null, new
           {

               type = "number",
               min = "0",
               step = "1",
               autocomplete = "off",
               @placeholder = " Bill Number ",
               @class = "form-control",
               @id = "DayID"
           })

            </div>
            <div class="form-group" style="margin-right:25px">

                @Html.TextBox("Date", null, new
       {
           @placeholder = " Date ",
           autocomplete = "off",
           @class = "datepicker form-control",
           @id = "DayDate"
       })
            </div>

            <div class="form-group">

                <input type="submit" value=" OK " class="form-control" id="Done" />
            </div>
        </div>

    }
</div>
<div id="MyId" align="center">
    <div style="margin-top:25px ; width:830px">
        <div style=" height:250px ; border:solid ">
            <img src="~/Content/themes/base/images/PIC1.PNG" height="150" width="400"
                 style="float:left; margin-left:4px ; margin-top:4px " />
         
            <div style="text-align:center ; margin-top: 10px ; font-weight:bold ; font-size:20px ">
                <p>ALFATEX</p>
            </div>
            <div style="float:right">
                <p>بيــــان أسعـــــار</p>
                <table>
                    <tr>
                        <td style="text-align:center ; width:150px">
                            @foreach (var item in Model)
                            {
                                @Html.DisplayFor(modelItem => item.CleintName)
                                break;
                            }

                        </td>
                        <th style="text-align:center ; width:150px">  مطلــوب من السيد </th>
                    </tr>
                    <tr>
                        <td style="text-align:center ; width:150px">

                            @foreach (var item in Model)
                            {
                                @Html.DisplayFor(modelItem => item.ClientID)
                                break;
                            }

                        </td>
                        <th style="text-align:center ; width:150px">كـــود العميل </th>
                    </tr>
                    <tr>
                        <td style="text-align:center ; width:150px">
                            @foreach (var item in Model)
                            {
                                @Html.DisplayFor(modelItem => item.Date)
                                break;
                            }
                        </td>
                        <th style="text-align:center ; width:150px">
                            تحريرا في

                        </th>
                    </tr>


                    <tr>
                        <td style="text-align:center ; width:150px">
                            @foreach (var item in Model)
                            {
                                @Html.DisplayFor(modelItem => item.BillNumber)
                                break;
                            }
                        </td>
                        <th style="text-align:center ; width:150px">
                            رقــم الفاتوره

                        </th>
                    </tr>


                    <tr>
                        <td style="text-align:center ; width:150px">
                            @foreach (var item in Model)
                            {
                                @Html.DisplayFor(modelItem => item.DailyID)
                                break;
                            }
                        </td>
                        <th style="text-align:center ; width:150px">
                            رقــم القــيد

                        </th>
                    </tr>
                </table>

            </div>



        </div>







        <table class=" table-bordered" align="center"
               style="margin-top:5px; border:solid ">
            <tr style="border:solid; ">
                <th style="text-align:center ;border-right:solid ; width:30px">
                    <p> S </p>
                </th>
                <th style="text-align:center ;border-right:solid ; width:100px">
                    <p> Code </p>
                </th>
                <th style="text-align:center;border-right:solid ; width:100px">
                    <p> Size </p>
                </th>
                <th style="text-align:center;border-right:solid ; width:300px ">
                    <p> Description </p>
                </th>
                <th style="text-align:center;border-right:solid; width:100px">
                    <p> Quantaty (بالكيس )</p>
                </th>
                <th style="text-align:center;border-right:solid; width:100px">
                    <p> Quantaty (بالدسته ) </p>
                </th>
                <th style="text-align:center;border-right:solid; width:100px">
                    <p>Price (بالجنيه)</p>
                </th>
                <th style="text-align:center; width:100px">
                    <p>Total(بالجنيه)</p>
                </th>

            </tr>

            @foreach (var item in Model)
            {


                <tr>
                    <td style="text-align:center">
                        @i
                        @{
                i++;
                        }
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.ProductID)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Size)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Bag)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Outgoing)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Total)
                    </td>
                </tr>
            }
            @for (int q = Model.Count() ; q < 22 ; q++)
            {
                <tr>
                    <td style="height:22px ; width:30px"></td>
                    <td style="height:22px; width:100px"></td>
                    <td style="height:22px ; width:100px"></td>
                    <td style="height:22px ; width:300px"></td>
                    <td style="height:22px ; width:100px"></td>
                    <td style="height:22px ; width:100px"></td>
                    <td style="height:22px ; width:100px"></td>
                    <td style="height:22px ; width:100px"></td>
                </tr>
            }
            <tr style="border-top:solid">
                <th style="text-align:center ;border-right:hidden ; width:30px">
                </th>
                <th style="text-align:center ;border-right:hidden ; width:100px">
                </th>
                <th style="text-align:center;border-right:hidden ; width:100px">
                </th>
                <th style="text-align:center;border-right:solid ; width:300px ">
                </th>
                <th style="text-align:center;border-right:solid; width:100px">
                    <p> @GBags</p>
                </th>
                <th style="text-align:center;border-right:solid; width:100px">
                    <p> @Goutgoing </p>
                </th>
                <th style="text-align:center;border-right:solid; width:100px">
                </th>
                <th style="text-align:center; width:100px">
                    <p>@GeneralTotal</p>
                </th>

            </tr>


        </table>


    </div>
</div>

<div align="center" style="margin-top:20px">
    <button onclick="print('MyId')" class="btn btn-default">  Print </button>
</div>

<script>
    function print(el) {
        var res = document.body.innerHTML;
        var p = document.getElementById(el).innerHTML;
        document.body.innerHTML = p;
        window.print();
        document.body.innerHTML = res;
    }
</script>



<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd MM yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10"
            });

        });

    </script>
}

ALFATEX4TRADE/Views/Primissions/Edit.cshtml
@model ALFATEX4TRADE.Models.RequestForm

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<div align="center">
    @using (Html.BeginForm("Edit", "Primissions", FormMethod.Post))
    {

        <div class="form-inline ">
            <div class="form-group" style="margin-right:25px">
                @Html.TextBox("PrimNumber", null, new
           {

               type = "number",
               min = "0",
               step = "1",
               autocomplete = "off",
               @placeholder = " Request Number ",
               @class = "form-control",
           })

            </div>
            <div class="form-group" style="margin-right:25px">

                @Html.TextBox("Date", null, new
       {
         
           @placeholder = " Date ",
           autocomplete = "off",
           @class = "datepicker form-control",
       })
            </div>

            <div class="form-group">

                <input type="submit" value="Edit" class="form-control" id="Done" />
            </div>
        </div>

    }
</div>



<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd MM yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10"
            });

        });
    </script>
}

ALFATEX4TRADE/Views/Primissions/EditReq.cshtml
@model ALFATEX4TRADE.Models.RequestForm

@{
    ViewBag.Title = "EditReq";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Stock Request </h2>


<hr />


@using (Html.BeginForm("EditReq", "Primissions", FormMethod.Post))
{

    <div align="center">

        <div class="form-inline ">
            <div class="form-group" style="margin-right:25px;width:150px">
            @Html.LabelFor(model => model.ClientID, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => Model.ClientID, new
           {
               @id = "CID",
               @class = "passcleint form-control",
               autocomplete = "off",
               @placeholder = " Cleint Code " ,
           })

            </div>
            <div class="form-group" style="margin-right:25px">
                @Html.LabelFor(model => model.CleintName, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => Model.CleintName, new
           {
               @id = "printcleint",
               autocomplete = "off",
               @class = "form-control",
               @placeholder = " Cleint Name "
           })


            </div>


        </div>
    </div>


    <table class=" table-bordered" align="center"
           style="margin-top:50px; border:solid ; ">
        <tr style="border:solid; ">
            <th style="text-align:center;border-right:solid">
                <p>Product Code </p>
            </th>
            <th style="text-align:center;border-right:solid">
                <p>Product Description </p>
            </th>
            <th style="text-align:center;">
                <p>Outgoing</p>
            </th>

        </tr>

        @for (int i = 0; i < 30; i++)
        {
            <tr>

                <td>
                    @Html.TextBoxFor(m => Model.ProductID, new { @id = "PID" + i, autocomplete = "off", @class = "passP form-control" })
                </td>

                <td>
                    @Html.TextBoxFor(m => Model.ProductName, new { @class = "form-control", @id = "printproduct" + i, autocomplete = "off" })

                </td>

                <td>
                    @Html.TextBoxFor(m => Model.Outgoing, new { @id = "out" + i, type = "number", min = "0", step = "1", autocomplete = "off", @class = "form-control" })
                </td>

            </tr>
        }
    </table>



    <div align="center" style="margin-top:20px ">
        <input type="submit" value="  Post  " class="btn btn-default" style="font-size: 20px" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.12.4.js"></script>


<script>

    $(document).ready(function () {

        $(window).keydown(function (event) {
            if (event.keyCode == 13) {
                event.preventDefault();
                return false;
            }
        });


        $(function () {
            $.get("DisplayEdit", {}, function (data) {
                $.each(data, function (i, v) {
                    $("#PID" + i).val(v.ProductID);
                    $("#printproduct" + i).val(v.ProductName);
                    $("#out" + i).val(v.Outgoing);
  
                    $("#CID").val(v.ClientID);
                    $("#printcleint").val(v.CleintName);

                });


            });
        });




        $("#CID").on('change', function () {
            var id = $("#CID").val();
            var Name;
            $(function () {
                $.get("Edit", {}, function (data) {
                    $.each(data, function (i, v) {
                        $("#PID" + i).val(v.ProductID);
                        $("#printproduct" + i).val(v.ProductName);
                        $("#CID").val(v.ClientID);
                        $("#printcleint").val(v.CleintName);

                    });


                });
            });

        });




        $(".passP").on('change', function () {
            var id = $(this).val();
            var ID = $(this).closest(".passP").attr("id");
            var Name;
            $(function () {
                $.get("GetProduct", {}, function (data) {
                    $.each(data, function (index, value) {
                        if (value.ProductID == id) {
                            Name = value.ProductName;
                        }
                    });
                    var last;
                    if (ID.length == 4) last = ID[3];
                    else last = ID[3] + ID[4];
                    $("#printproduct" + last).val(Name);

                });
            });

        });

    });
</script>