ALFATEX4TRADE/Models/Stocktaking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ALFATEX4TRADE.Models
{
    public class Stocktaking
    {
             [Display(Name = "Account Code")]

        public string CleintID { get; set; }

                              [Display(Name = "Account Name")]

        public string CleintName { get; set; }

                              [Display(Name = "Product Code")]

        public string ProductID { get; set; }

                              [Display(Name = "Product Description")]

        public string ProductName { get; set; }

        public string Size { get; set; }

        public double Incoming { get; set; }

        public double Outgoing { get; set; }

        public double Balance { get; set; }

                              [Display(Name = "Cleint Outgoing")]

        public double CleintOutgoing { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        [Display(Name = "Opening Date")]

        public DateTime? OpeningDate { get; set; }


        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]

        [Display(Name = "Ending Date")]

        public DateTime? EndingDate { get; set; }


    }
}

ALFATEX4TRADE/Controllers/StockTakingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ALFATEX4TRADE.Models;

namespace ALFATEX4TRADE.Controllers
{
    public class StockTakingController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationDbContext db2 = new ApplicationDbContext();
         public   List<Stocktaking> list = new List<Stocktaking>();
        // GET: StockTaking
        [Authorize]
        public ActionResult Index()
        {

            Stocktaking s = new Stocktaking();
            s.OpeningDate = DateTime.MinValue;
            s.EndingDate = DateTime.MaxValue;
            clc(s);
            return View(list);
        }
        [HttpPost]
        public ActionResult Index( Stocktaking st )
        {

                foreach (var i in db.Cleint)
                {
                    if (i.AccountID == st.CleintID)
                    {
                        st.CleintName = i.AccountName;
                        break;
                    }
                }
                 
            if (ModelState.IsValid)
            {

                if (st.OpeningDate == null)
                {
                    st.OpeningDate = DateTime.MinValue;
                }
                if (st.EndingDate == null)
                {
                    st.EndingDate = DateTime.MaxValue;
                }
                clc(st);

            }
            return View(list);
        }


        public void clc(Stocktaking st )
        {

            foreach (var i in db.Product)
            {
                Stocktaking cur = new Stocktaking();
                cur.CleintID = st.CleintID;
                cur.CleintName = st.CleintName;
                cur.ProductID = i.ProductID;
                cur.ProductName = i.Description;
                cur.Incoming = Convert.ToDouble(i.Incoming);
                cur.Size = i.Size;
                cur.OpeningDate = st.OpeningDate;
                cur.EndingDate = st.EndingDate;
                foreach (var j in db2.Primission)
                {
                    if (j.ProductID == i.ProductID &&
                        j.Date >= cur.OpeningDate && j.Date <= cur.EndingDate)
                    {
                        cur.Outgoing += j.Outgoing;

                        if (j.ClientID == cur.CleintID)
                        {
                            cur.CleintOutgoing += j.Outgoing;
                        }
                    }
                }
                cur.Balance = cur.Incoming - cur.Outgoing;
                list.Add(cur);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ALFATEX4TRADE/Views/StockTaking/Index.cshtml
@model  IEnumerable<ALFATEX4TRADE.Models.Stocktaking>


@{
    ViewBag.Title = "Stocktaking";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Stocktaking </h2>
<div align="center">
    @using (Html.BeginForm("Index", "StockTaking", FormMethod.Post))
    {

        <div class="form-inline">

            <div class="form-group" style="margin-right:25px">
                @Html.TextBox("CleintID", null,
                new
                {
      
                    @class = "form-control",
                    @placeholder = " Cleint Code ",
                    @autocomplete = "off"
                })
            </div>


            <div class="form-group" style="margin-right:25px">
                @Html.TextBox("OpeningDate", null, new
           {
               @placeholder = " Opening Date ",
               autocomplete = "off",
               @class = "datepicker form-control"

           })

            </div>
            <div class="form-group" style="margin-right:25px">

                @Html.TextBox("EndingDate", null, new
       {

           @placeholder = "Ending Date ",
           autocomplete = "off",
           @class = "datepicker form-control"

       })
            </div>

            <div class="form-group">

                <input type="submit" value=" OK " class="form-control" id="Done" />
            </div>
        </div>

    }
</div>
<div align="center">

    <div style="margin-top:25px ; max-width:800px ; border:solid">


        <div style="border-bottom:solid ; height:60px ; ">
            <div>
                <span style="margin-right:5px; font-weight:bold ;font-size:20px; margin-left:8px "> Cleint Name : </span>
                @foreach (var item in Model)
                {
                    <span style="font-size:18px; margin-right:20px">
                        @Html.DisplayFor(modelItem => item.CleintName)
                    </span>
                    break;
                }
            </div>
            </div>




            <table class="table table-bordered">
                <tr style="border-bottom:solid">
                    <th style="text-align:center ; border-right:solid">
                        @Html.DisplayNameFor(model => model.ProductID)
                    </th>

                    <th style="text-align:center; border-right:solid">
                        @Html.DisplayNameFor(model => model.ProductName)
                    </th>

                    <th style="text-align:center; border-right:solid">
                        @Html.DisplayNameFor(model => model.Size)
                    </th>

                    <th style="text-align:center; border-right:solid">
                        @Html.DisplayNameFor(model => model.Incoming)
                    </th>
                    <th style="text-align:center; border-right:solid">
                        @Html.DisplayNameFor(model => model.Outgoing)
                    </th>
                    <th style="text-align:center; border-right:solid">
                        @Html.DisplayNameFor(model => model.Balance)
                    </th>
                    <th style="text-align:center">
                        @Html.DisplayNameFor(model => model.CleintOutgoing)
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.ProductID)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.ProductName)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.Size)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.Incoming)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.Outgoing)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.Balance)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.CleintOutgoing)
                        </td>
                    </tr>
                }

            </table>
        </div>
</div>




<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd MM yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10"
            });

        });
    </script>
}