ALFATEX4TRADE/Models/Data.cs
namespace ALFATEX4TRADE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class Data
    {
        public int ID { get; set; }

        [Display(Name = "Journal Entry Number  ")]
        public int DailyNum { get; set; }

        [Display(Name = " Code ")]
        public string AccountID { get; set; }

      [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]

        public DateTime? Date { get; set; }
        public Nullable<double> DR { get; set; }
        public Nullable<double> CR { get; set; }

                [Display(Name = "Account")]

        public string AccountName { get; set; }

         public string Description { get; set; }

    }
}

ALFATEX4TRADE/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ALFATEX4TRADE.Models;

namespace ALFATEX4TRADE.Controllers
{
    public class DataController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Data
         [Authorize]

        public ActionResult Index()
        {
            int n = 0 ;
            foreach (var i in db.Data)
            {
                if (i.DailyNum > n && i.Date ==  DateTime.Today ) n = i.DailyNum;
            }
            return View(db.Data.Where(x => x.DailyNum == n && x.Date == DateTime.Today).ToList());
        }


        [HttpPost]

        public ActionResult Index(Data data )
        {
            if (ModelState.IsValid)
            {
                return View(db.Data.Where(x => x.DailyNum == data.DailyNum && x.Date == data.Date).ToList());
            }

            return RedirectToAction("Index");
        }


          [Authorize]
        public ActionResult AccountData()
        {
            return View(db.Data.Where(x => x.AccountID == "").ToList());
        }

        [HttpPost]
          public ActionResult AccountData(ChartOfAccounts c) 
          {
              if (ModelState.IsValid)
              {
                  if (c.OpeningDate == null)
                  {
                      c.OpeningDate = DateTime.MinValue;
                  }
                  if (c.EndingDate == null)
                  {
                      c.EndingDate = DateTime.MaxValue;
                  }


                  OpeningAndEnding op = new OpeningAndEnding();

                  foreach (var i in db.Balance)
                  {
                          db.Balance.Remove(i);
                      
                  }

                  foreach (var j in db.Data)
                  {
                      if (c.AccountID == j.AccountID)
                      {
                          if (j.Date <= c.OpeningDate)
                          {

                              op.OpeningBalace += Convert.ToDouble(j.DR);
                              op.OpeningBalace -= Convert.ToDouble(j.CR);
                          }
                          if (j.Date <= c.EndingDate)
                          {
                   
                              op.EndingBalace += Convert.ToDouble(j.DR);
                              op.EndingBalace -= Convert.ToDouble(j.CR);
                          }

                      }
                  }

                  db.Balance.Add(op);
                  db.SaveChanges();


                  return View(db.Data.Where(x => x.AccountID == c.AccountID && x.Date > c.OpeningDate &&
                      x.Date <= c.EndingDate).ToList());
              }
              return RedirectToAction("AccountData");
          }


         [Authorize]

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create (DailyTradeForm DF)
        {
            double dr = 0, cr = 0;
            for (int i = 0; i < DF.AccountID.Count(); i++)
            {
                if (DF.AccountID[i].Length == 0) continue;
                dr += DF.DR[i];
                cr += DF.CR[i];
            }

            if (dr != cr)
            {
               
                return View();

            }

            int dailyNum = 0;
            DateTime date = DateTime.Today;
            foreach (var i in db.Data)
            {
                if (i.Date == date && i.DailyNum >dailyNum )
                {
                    dailyNum = i.DailyNum ;
                }
            }

            dailyNum++;
            for (int i = 0; i < DF.AccountID.Count(); i++)
            {
                if (DF.AccountID[i].Length == 0 ) continue;
                Data data = new Data();
                data.DailyNum = dailyNum;
                data.Date = DateTime.Today;
                data.AccountID = DF.AccountID[i];
                data.CR = DF.CR[i] ;
                if (data.CR == 0) data.CR = null;
                data.DR = DF.DR[i];
                if (data.DR == 0) data.DR = null;
                data.AccountName = DF.AccountName[i] ;
              data.Description = DF.Description[i] ;
                db.Data.Add(data);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public JsonResult GetName()
        {
            List<DailyTradeRecord> IdName = new List<DailyTradeRecord>();
            foreach (var i in db.Cleint)
            {
                IdName.Add(new DailyTradeRecord
                {
                    AccountID= (i.AccountID).ToString(),
                    AccountName = (i.AccountName).ToString()

                });
            }
            return Json(IdName, JsonRequestBehavior.AllowGet);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ALFATEX4TRADE/Views/Data/AccountData.cshtml
@model IEnumerable<ALFATEX4TRADE.Models.Data>

@{
    ViewBag.Title = "AccountData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Account Statement</h2>

<div align="center" style="margin-bottom:25px">

    @using (Html.BeginForm("AccountData", "Data", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-inline">
            <div class="form-group" style="margin-right:25px">
                @Html.TextBox("AccountID", null,
                new { @class = "form-control", @placeholder = " Account Code ", @autocomplete = "off" })
            </div>

            <div class="form-group" style="margin-right:25px">
                @Html.TextBox("OpeningDate", null, new
           {
               @placeholder = " Opening Date ",
               autocomplete = "off",
               @class = "datepicker form-control"

           })

            </div>
            <div class="form-group" style="margin-right:10px">

                @Html.TextBox("EndingDate", null, new
       {

           @placeholder = "Ending Date ",
           autocomplete = "off",
           @class = "datepicker form-control"

       })
            </div>



            <div class="form-group" style="margin-left:15px">
                <input type="submit" value=" OK " class="btn btn-default" />
            </div>
        </div>

    }
</div>
<div align="center">

    <div style="margin-top:25px ; max-width:800px ; border:solid">


        <div style="border-bottom:solid ; height:60px ; ">
            <div>
                <span style="margin-right:5px; font-weight:bold ;font-size:20px; margin-left:8px "> Account Name : </span>
                @foreach (var item in Model)
                {
                    <span style="font-size:18px; margin-right:20px">
                        @Html.DisplayFor(modelItem => item.AccountName)
                    </span>
                    break;
                }
            </div>
        </div>




        <table class="table table-bordered">
            <tr style="border-bottom:solid">
                <th style="text-align:center ; border-right:solid ;width:200px">
                    @Html.DisplayNameFor(model => model.DailyNum)
                </th>

                <th style="text-align:center; border-right:solid">
                    @Html.DisplayNameFor(model => model.Date)
                </th>

                <th style="text-align:center; border-right:solid">
                    @Html.DisplayNameFor(model => model.DR)
                </th>

                <th style="text-align:center;border-right:solid">
                    @Html.DisplayNameFor(model => model.CR)
                </th>

                <th style="text-align:center;">
                    @Html.DisplayNameFor(model => model.Description)
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.DailyNum)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.DR)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.CR)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>

                </tr>
            }

        </table>
    </div>
</div>




<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd MM yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10"
            });

        });
    </script>
}

ALFATEX4TRADE/Views/Data/Create.cshtml
@model ALFATEX4TRADE.Models.DailyTradeForm

@{
    ViewBag.Title = "Create";
}

<h2> New Journal Entry </h2>

@using (Html.BeginForm("Create", "Data", FormMethod.Post))
{


    <table class=" table-bordered" align="center"
           style="margin-top:50px; border:solid ; ">
        <tr style="border:solid; ">
            <th style="text-align:center ;border-right:solid">
                <p>Code</p>
            </th>
            <th style="text-align:center;border-right:solid">
                <p> Account </p>
            </th>
            <th style="text-align:center;border-right:solid">
                <p>DR</p>
            </th>
            <th style="text-align:center;border-right:solid">
                <p>CR </p>
            </th>

            <th style="text-align:center;">
                <p>Description </p>
            </th>
        </tr>

        @for (int i = 0; i < 30; i++)
        {
            <tr>
                <td >
                    @Html.TextBoxFor(m => Model.AccountID[i], new { @id = "ID" + i, @class = "pass form-control", autocomplete = "off" })
                </td>

                <td>
                    @Html.TextBoxFor(m => Model.AccountName[i], new { @id = "print" + i, autocomplete = "off", @class = "form-control" })
                </td>

                <td>
                    @Html.TextBoxFor(m => Model.DR[i], new { @id ="dr"+i , type = "number", min = "0", step = "1", autocomplete = "off", @class = "form-control" })
                </td>

                <td>
                    @Html.TextBoxFor(m => Model.CR[i], new { @id = "cr" + i , type = "number", min = "0", step = "1", autocomplete = "off", @class = "form-control" })

                </td>
                <td>
                    @Html.TextBoxFor(m => Model.Description[i], new {  autocomplete = "off", @class = "form-control" })
                </td>
            </tr>
        }
    </table>



    <div align="center" style="margin-top:20px ">
        <input type="submit" value="  Post  " class="btn btn-default" style="font-size: 20px" id="post" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.12.4.js"></script>
<script>

    $(document).ready(function () {

        $("#post").on("click", function () {
            var dr = parseFloat(0);
            var cr = parseFloat(0);
          //  alert(dr);
            for (var i = 0 ; i < 20 ; i++) {

              if ( ($("#dr" + i).val()).length > 0 ){
                dr += parseFloat($("#dr" + i).val())  ;
                }
              if (($("#cr" + i).val()).length > 0) {
                    cr += parseFloat($("#cr" + i).val());
                } 
                }
            if (dr != cr) {
                var newLine = "\r\n"
                var msg = "Total DR = " + dr + newLine + "Total CR = " + cr +
                    newLine + " Total DR & Total CR are NOT equal ";
                alert(msg);
            }
        });





        $(window).keydown(function (event) {
            if (event.keyCode == 13) {
                event.preventDefault();
                return false;
            }
        });

        $(".pass").on('change', function () {
            var id = $(this).val();
            var ID = $(this).closest(".pass").attr("id");
            var Name;
           $(function () {
                $.get("GetName", {}, function (data) {
                    $.each(data, function (index, value) {
                        if ( value.AccountID == id) {
                            Name = value.AccountName ;
                        }
                    });
                    var last;
                    if (ID.length == 3) last = ID[2];
                    else last = ID[2] + ID[3];
                    $("#print" + last).val(Name);

                });
            });

        });
        //   }
    
    });
</script>

ALFATEX4TRADE/Views/Data/Delete.cshtml
@model ALFATEX4TRADE.Models.Data

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Data</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DailyNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DailyNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ALFATEX4TRADE/Views/Data/Details.cshtml
@model ALFATEX4TRADE.Models.Data

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Data</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DailyNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DailyNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ALFATEX4TRADE/Views/Data/Edit.cshtml
@model ALFATEX4TRADE.Models.Data

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Data</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.DailyNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DailyNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DailyNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ALFATEX4TRADE/Views/Data/Index.cshtml
@model IEnumerable<ALFATEX4TRADE.Models.Data>

@{
    ViewBag.Title = "Index";
}

<h2>Journal Entry</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div align="center">
@using (Html.BeginForm("Index", "Data", FormMethod.Post))
{

    <div class="form-inline ">
        <div class="form-group" style="margin-right:25px">
            @Html.TextBox("DailyNum", null, new
           {
              
               autocomplete="off",
               @placeholder = " Daily Number ",
               @class = "form-control",
               @id = "DayID"
           })

        </div>
        <div class="form-group" style="margin-right:25px">

            @Html.TextBox("Date", null, new
       {
           @Value = DateTime.Today.ToString("dd MMM yyyy"),
           @placeholder = " Date ",
           autocomplete="off",
           @class = "datepicker form-control",
           @id = "DayDate"
       })
        </div>

        <div class="form-group">

            <input type="submit" value="OK " class="form-control" id="Done" />
        </div>
    </div>

}
</div>

<div id="MyId" align="center">
<div style="margin-top:25px ; max-width:800px ; border:solid" >

    <div style="border-bottom:solid ; height:70px ; ">
        <div>
            <span style="margin-right:5px; font-weight:bold ;font-size:20px; margin-left:8px "> Journal Entry Number : </span>
            @foreach (var item in Model)
            {
                <span style="font-size:18px; margin-right:20px">
                    @Html.DisplayFor(modelItem => item.DailyNum)
                </span>
                break;
            }
        </div>
        <span style="margin-right:5px ; font-weight:bold ;font-size:20px; margin-left:8px  "> @Html.DisplayNameFor(model => model.Date) :</span>

        @foreach (var item in Model)
        {
            <span style="font-size:18px ; margin-right:20px">
                @Html.DisplayFor(modelItem => item.Date)
            </span>
            break;
        }



    </div>

    <table class="table table-bordered">
        <tr style="border-bottom:solid">
            <th style="text-align:center ; border-right:solid">
                @Html.DisplayNameFor(model => model.AccountID)
            </th>

            <th style="text-align:center ; border-right:solid">
                @Html.DisplayNameFor(model => model.AccountName)
            </th>

            <th style="text-align:center ; border-right:solid">
                @Html.DisplayNameFor(model => model.DR)
            </th>
            <th style="text-align:center ; border-right:solid">
                @Html.DisplayNameFor(model => model.CR)
            </th>

            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.Description)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.AccountID)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.AccountName)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.DR)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.CR)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
            </tr>
        }

    </table>

</div>
</div>
<div align="center" style="margin-top:20px">
    <button onclick="print('MyId')" class="btn btn-default">  Print </button>
</div>

<script>
    function print(el) {
        var res = document.body.innerHTML;
        var p = document.getElementById(el).innerHTML;
        document.body.innerHTML = p;
        window.print();
        document.body.innerHTML = res;
    }
</script>


<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{

<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd MM yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10"
            });

        });
    </script>
}